[workspaces]
enable = true

[install]
exact = true
lockfile = true
peer = true
production = false
registry = "https://registry.npmjs.org/"
strategy = "yarn"

[build]
minify = true
sourcemap = true
external = ["@grpc/*", "pino", "fastq"]

[test]
coverage = true
preload = "./scripts/registerPathAlias.js"

[dev]
port = 3000
open = false

[typescript]
prefer-types = true

[turbo]
enabled = true

[resolve]
"@core/*" = "./packages/core/src/core/*"
"@utils/*" = "./packages/core/src/utils/*"
"@testing/*" = "./packages/core/src/testing/*"
"@monitoring/*" = "./packages/core/src/monitoring/*"
