[workspaces]
enable = true

[install]
exact = true
lockfile = true
peer = true
production = false
registry = "https://registry.npmjs.org/"

[build]
minify = true
sourcemap = true
external = ["@grpc/*", "pino", "fastq"]

[test]
coverage = true

[dev]
port = 3000
open = false

[typescript]
prefer-types = true

[turbo]
enabled = true
